<?php 
/*--------------------------------------------------------------------------------------*\
| ADD COLOURS PAGE
\*--------------------------------------------------------------------------------------*/


function ACF_colourspage() {
 			if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63b5937715da0',
	'title' => 'Colours',
	'fields' => array(
		array(
			'key' => 'field_63b593779a4e1',
			'label' => 'Colours',
			'name' => 'colours',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_63b593809a4e2',
					'label' => 'Default text color',
					'name' => 'default_text_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b593a39a4e3',
					'label' => 'Accent text color one',
					'name' => 'accent_text_color_one',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b593c09a4e5',
					'label' => 'Accent text color two',
					'name' => 'accent_text_color_two',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b593c19a4e6',
					'label' => 'Accent text color three',
					'name' => 'accent_text_color_three',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b593bc9a4e4',
					'label' => 'Default background color',
					'name' => 'default_background_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b593ec9a4e8',
					'label' => 'Accent background color one',
					'name' => 'accent_background_color_one',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b593f79a4e9',
					'label' => 'Accent background color two',
					'name' => 'accent_background_color_two',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b594029a4ea',
					'label' => 'Accent background color three',
					'name' => 'accent_background_color_three',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b594209a4eb',
					'label' => 'Default filled button text color',
					'name' => 'default_filled_button_text_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b5944d9a4ec',
					'label' => 'Default filled button background color',
					'name' => 'default_filled_button_background_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b594fd9a4ed',
					'label' => 'Default outlined button text color',
					'name' => 'default_outlined_button_text_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
				array(
					'key' => 'field_63b595039a4ee',
					'label' => 'Default outlined button background color',
					'name' => 'default_outlined_button_background_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'Colours',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		
}
if( function_exists('acf_add_local_field_group') ){
    add_action('acf/init', 'ACF_colourspage');
}
    
/*--------------------------------------------------------------------------------------*\
| ADD OPTIONS PAGE
\*--------------------------------------------------------------------------------------*/
function ACF_optionspage() {
    acf_add_local_field_group(array(
        'key' => 'group_636a22febcae7',
        'title' => 'Options page',
        'fields' => array(
            array(
                'key' => 'field_636a243b64401',
                'label' => 'Gegevens',
                'name' => 'gegevens',
                'type' => 'group',
                'instructions' => 'Insert company info',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_636a244d64402',
                        'label' => 'Email',
                        'name' => 'email',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_636a245464403',
                        'label' => 'Phone',
                        'name' => 'telefoon_nummer',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_636a246c64404',
                        'label' => 'Street + number',
                        'name' => 'straat_nummer',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_636a248164405',
                        'label' => 'Location + postalcode',
                        'name' => 'gemeente_postcode',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_636a258c8634f',
                        'label' => 'Name company',
                        'name' => 'naam_bedrijf',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_636a23b4a16cf',
                        'label' => 'registered office adress',
                        'name' => 'maatschappelijke_zetel',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_636a23afa16ce',
                        'label' => 'Enterprise number',
                        'name' => 'ondernemingsnummer',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'Settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
}
if( function_exists('acf_add_local_field_group') ){
    add_action('acf/init', 'ACF_optionspage');
}
